sudo: required
services:
  - docker

before_install :
  - docker build -t rageshramesh4/docker-react -f Dockerfile.dev .

script :
  - docker run -e CI=true rageshramesh4/docker-react npm run test

deploy :
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react-1"
  env: "Docker-react-1-env"
  bucket_name: "elasticbeanstalk-ap-south-1-906842860323"
  bucket_path : "docker-react-1"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY